
Vagrant.configure(2) do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
      vb.customize ['modifyvm', :id, '--nicpromisc0', 'allow-all']
      vb.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
      vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']

      vb.cpus = 2
  end

  config.vm.synced_folder "../macsec", "/vagrant/macsec"
  config.vm.provision "shell", path: "scripts/install-dependencies.sh", run: "once"
  #config.vm.provision "shell", path: "scripts/disable-aes.sh", run: "once"
  # trigger reload
  config.vm.provision :reload, run: "once"
  #config.vm.provision "shell", path: "scripts/install-kedr.sh", run: "once"

  config.vm.define "vbox1" do |vbox1|
    vbox1.vm.network "private_network", ip: "192.168.56.11", mac: "00133b0fc796", auto_config: true

    vbox1.vm.hostname = "vbox1"

    vbox1.vm.provision "shell", path: "scripts/conf-macsec.sh", run: "always", env: {
         "IP" => "1.1.1.1",
         "MY_MAC" => "00:13:3b:0f:c7:96",
         "PARTNER_MAC" => "00:13:3b:0f:c7:97",
         "MY_KEY" => "22222222222222222222222222222222",
         "PARTNER_KEY" => "11111111111111111111111111111111"}
  end

  config.vm.define "vbox2" do |vbox2|
    vbox2.vm.network "private_network", ip: "192.168.56.12", mac: "00133b0fc797", auto_config: true

    vbox2.vm.hostname = "vbox2"

    vbox2.vm.provision "shell", path: "scripts/conf-macsec.sh", run: "always", env: {
      "IP" => "1.1.1.2",
      "MY_MAC" => "00:13:3b:0f:c7:97",
      "PARTNER_MAC" => "00:13:3b:0f:c7:96",
      "MY_KEY" => "11111111111111111111111111111111",
      "PARTNER_KEY" => "22222222222222222222222222222222"}
  end
end
